config/routes.rb
Rails.application.routes.draw do
  get 'projects/search', to: "projects#search", as: :project_search

  resources :projects, only: [:index, :show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :skip => [:registrations]
  
  post '', to: "presentation#create", as: :contacts

  root to: "presentation#about"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all                 # allow everyone to read everything
    return unless user && user.admin?
    can :access, :rails_admin       # only allow admin users to access Rails Admin
    can :read, :dashboard           # allow access to dashboard
    can :manage, :all  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}_tags", value) if value.present?
      end
      
      results
    end
  end
end

app/models/concerns/tag_manager.rb
module TagManager
    extend ActiveSupport::Concern

    def all_tags
        tag_list = []
        contexts = self.class.class_variable_get(:@@contexts)

        contexts.each do |context|
           tag_list.concat self.tag_list_on(context)
        end
        
        tag_list
    end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      validate: true
    attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :subject,   validate: true
    attribute :message,   validate: true
    attribute :nickname,  captcha: true

    def headers
      {
        :subject => "Portfolio Contact Message",
        :to => "caiow2001+dev@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/link.rb
class Link < ApplicationRecord
    has_and_belongs_to_many :projects
    has_and_belongs_to_many :profiles
    belongs_to :link_type

    validates :name, presence: true, uniqueness: true
    validates :link, presence: true, uniqueness: true
    validates :tooltip, presence: true
end

app/models/link_type.rb
class LinkType < ApplicationRecord
    has_many :links

    validates :type_name, presence: true, uniqueness: true
    validates :icon, presence: true, uniqueness: true
end

app/models/profile.rb
class Profile < ApplicationRecord
    include ImageUploader::Attachment(:picture)

    @@contexts = [:technologies, :skills]

    include TagManager
    
    has_and_belongs_to_many :projects
    has_and_belongs_to_many :links

    acts_as_taggable_on(*@@contexts)
end

app/models/project.rb
class Project < ApplicationRecord
  include GifUploader::Attachment(:gif_image)

  @@contexts = [:technologies, :skills]

  include TagManager
  include Filterable

  has_and_belongs_to_many :profiles
  has_and_belongs_to_many :links

  acts_as_taggable_on(*@@contexts)

  scope :filter_by_all_tags, ->(tags) {
          self.tagged_with(tags, :any => true)
        }

  validates_presence_of :title, :description, :resume_card, :body

  def demo_link
    self.links.where(link_type_id: LinkType.where(type_name: "demo").first.id).first
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
  before_action :set_profile, only: [:about, :create]

  def about
    @contact = Contact.new
    return @profile, @contact
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request

    if @contact.deliver
      flash.now[:primary] = ['Message sent!']
    else
      flash.now[:danger] = @contact.errors.full_messages
    end

    @contact = Contact.new
    render "about"
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message, :nickname)
  end

  def set_profile
    @profile = Profile.find(1)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show ]
  before_action :parse_search_query, only: [:search]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  def search
    @projects = Project.filter(params.slice(:all))
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def parse_search_query
      search_query = params[:query]
      if search_query.present?
        params[:all] = search_query.split(",").map do |term|
          term.strip
        end
      end
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{width}x#{height}"
  end

  def project_img(img, type)
    if img.present?
      img
    elsif type == "thumb"
      image_generator(height: "250", width: "400")
    elsif type == "main"
      image_generator(height: "450", width: "800")
    end
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      language ||= :plaintext
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      no_intra_emphasis: true,
      space_after_headers: true,
      tables: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/layouts/_nav_dark_layout.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <%= link_to root_path, id: "logo", class: "navbar-brand logo-white" do %> <%=
  image_tag("logo.svg", size: "130x40") %> <% end %>
  <%= yield %>
</nav>

app/views/layouts/_nav_light_layout.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <%= link_to root_path, id: "logo", class: "navbar-brand logo-dark" do %> <%=
  image_tag("logo.svg", size: "130x40") %> <% end %>
  <%= yield %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 

    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Festive&family=Pacifico&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <%= yield %>
    
    <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" />
    <script>
      MathJax = {
        tex: {
          inlineMath: [['$', '$'], ['\\(', '\\)']]
        }
      };
      </script>
  </body>
</html>

app/views/shared/_link.html.erb
<div class="row py-2">
  <a href="<%= link.link %>" target="_blank" data-toggle="tooltip" data-placement="bottom" title="<%= link.tooltip %>"><%= icon("fab", link.link_type.icon) %></a>
</div>

app/views/shared/_nav.html.erb
<button
  class="navbar-toggler"
  type="button"
  data-toggle="collapse"
  data-target="#navbarNavDropdown"
  aria-controls="navbarNavDropdown"
  aria-expanded="false"
  aria-label="Toggle navigation"
>
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to "Sobre", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Contato", root_path(anchor: 'contact'), class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Ver Projetos", projects_path, class: "btn btn-outline-info"
      %>
    </li>
  </ul>
</div>

app/views/shared/_project_item.html.erb
<div class="col-12 col-md-4 my-4">
  <div href="" class="project-item custom-card">
    <div class="row image-hover">
        <%= image_tag project_img(project_item.gif_image_url(:static), "thumb"), width: 400,
        height: 250, class: "card__image static" %>
        <%= image_tag project_img(project_item.gif_image_url, "thumb"), width: 400,
        height: 250, class: "card__image animated" %>

      <div class="container card__image-buttons">
        <div class="row justify-content-end">
          <a
            class="resume-button rounded-circle"
            role="button"
            data-toggle="modal"
            data-target="#resume<%= project_item.id %>"
          >
            <%= icon("fas", "eye") %>
          </a>
        </div>
        <div class="row justify-content-center">
          <%= link_to "Read More", project_path(project_item.id), class: "btn
          btn-outline-dark btn-lg" %>
        </div>
      </div>
    </div>
    <div class="description-hover">
      <div class="card__overlay">
        <div class="row card__header">
          <div class="card__header-text">
            <h3 class="card__title"><%= project_item.title %></h3>
            <span class="card__tagline">
              <%= render partial: "shared/tag", collection:
              project_item.technologies[0..4], locals: {_classes: "badge
              badge-pill badge-info"} %>
            </span>
          </div>
        </div>
        <div class="row">
          <p class="card__description"><%= project_item.description %></p>
        </div>
        <% if project_item.demo_link %>
        <div class="row justify-content-center mb-4">
          <%= link_to "demo", project_item.demo_link.link, target: :_blank, class:
          "demo-btn btn btn-info btn-sm px-3" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div
  class="modal fade"
  id="resume<%= project_item.id %>"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Resume</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <%= render partial: "shared/tag", collection: project_item.all_tags,
          locals: {_classes: "badge badge-pill badge-info m-2"} %>
        </div>
        <hr />
        <div id="markdown" class="row p-3"><%= markdown project_item.resume_card %></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <%= link_to "Read More", project_path(project_item.id), class: "btn
        btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tag.html.erb
<span
  class="<%= _classes %>"
  ><%= tag %></span
>