config/routes.rb
Rails.application.routes.draw do
  get 'projects/search', to: "projects#search", as: :project_search

  resources :projects, only: [:index, :show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :skip => [:registrations]
  
  post '', to: "presentation#create", as: :contacts

  root to: "presentation#about"

end

app/models/project.rb
class Project < ApplicationRecord
  include GifUploader::Attachment(:gif_image)

  @@contexts = [:technologies, :skills]

  include TagManager
  include Filterable

  has_and_belongs_to_many :profiles
  has_and_belongs_to_many :links

  acts_as_taggable_on(*@@contexts)

  scope :filter_by_all_tags, ->(tags) {
          self.tagged_with(tags, :any => true)
        }

  validates_presence_of :title, :description, :resume_card, :body

  def demo_link
    self.links.where(link_type_id: LinkType.where(type_name: "demo").first.id).first
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show ]
  before_action :parse_search_query, only: [:search]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  def search
    @projects = Project.filter(params.slice(:all))
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def parse_search_query
      search_query = params[:query]
      if search_query.present?
        params[:all] = search_query.split(",").map do |term|
          term.strip
        end
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{width}x#{height}"
  end

  def project_img(img, type)
    if img.present?
      img
    elsif type == "thumb"
      image_generator(height: "250", width: "400")
    elsif type == "main"
      image_generator(height: "450", width: "800")
    end
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      language ||= :plaintext
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      no_intra_emphasis: true,
      space_after_headers: true,
      tables: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/projects/_project_not_found.html.erb
<div class="projects-not-found">
  <i class="fas fa-grimace"></i>
  <p>Projetos não encontrados</p>
</div>

app/views/projects/index.html.erb
<div id="projects-navbar">
  <%= render partial: 'shared/nav', layout: 'layouts/nav_light_layout' %>
</div>

<div id="projects">
  <div class="bg-dark py-5">
    <div class="container py-5 px-5">
      <div class="row justify-content-center">
        <div class="col">
          <div class="text-center my-5">
            <h1 class="display-5 fw-bolder text-white mb-2">Meus Projetos</h1>
            <p class="lead text-white-50 mb-4">
              Encontre meus projetos aqui.<br>
               Filtre por tecnologias usadas ou 
              por skills relacionadas. <br>
              Ex: python, ruby, software engineer, finance
            </p>
          </div>
        </div>
      </div>
          <div class=" row pb-5 mb-4 input-group justify-content-center">
            <%= form_with url: project_search_path, method: :get, html: {class: "form-inline"} do |form| %>
              <div class="row ml-4 ml-md-0">
                <div class="col-md col-sm-12 px-0">
                  <%= form.text_field :query , class: "form-control", placeholder: "Tecnologias... (Ex: python, heroku)"%>
                </div>
                <div class="col-md col-sm-12 px-0">
                  <button type="submit" class="col btn btn-info">
                    <%= icon("fas", "search") %>
                  </button>
                </div>
              </div>
            <% end %>
          </div>
    </div>
  </div>
  <div class="container-fluid py-5">
    <div class="row">
      <div class="col">
        <% if !@projects.empty? %>
          <div class="cards">
            <div class="row">
            <%= render partial: "shared/project_item", collection: @projects %>
            </div>
          </div>
        <% else %>
          <%= render "project_not_found" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'projects' %>
<%= javascript_pack_tag 'changeNavLogo' %>

app/views/projects/show.html.erb
<%= render partial: 'shared/nav', layout: 'layouts/nav_dark_layout' %>

<div class="project-show container-fluid mt-5 pt-3 px-0 mx-0">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 mx-0">
      <div class="cards mx-0">
        <div id="project-article" class="card mx-0">
          <div class="card-header pl-5">
            <div class="row pl-2">
              <h1 class="card-title"><%= @project.title %></h1>
            </div>
            <div class="row pl-2">
              <span class="card-subtitle mb-2 text-muted description"
                ><%= @project.description %></span
              >
            </div>
            <div class="row">
              <%= render partial: "shared/tag", collection: @project.all_tags,
              locals: {_classes: "custom-badge custom-badge-info
              custom-badge-outlined badge-pill m-2"} %>
            </div>
          </div>
          <div class="card-body mb-4">
            <div class="card-text">
              <div class="row mb-5">
                <%= image_tag project_img(@project.gif_image_url, "main"), width:
                800, height: 450, class: "card-img" %>
              </div>
              <div id="markdown" class="">
                <p><%= markdown @project.body %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
  </div>

  </div>
  <div class="social-div">
    <%= render partial: 'shared/link', collection: @project.links %>
  </div>
</div>